insert into roles (name) values ('ROLE_ADMIN');
insert into roles (name) values ('ROLE_USER');

INSERT INTO clientes (id_cliente, apellido_cliente, correo_electronico_cliente, direccion_cliente, documento_identidad, nombre_cliente, telefono_cliente) VALUES (1, 'Navarro', 'duvandavid2001@gmail.com', 'Mz 6 C 11 Andrea Carolina', '1004377901', 'Duvan', '3218035524');
INSERT INTO users (id, email, password, username, cliente_id_cliente) VALUES (1, 'admin@gmail.com', '$2a$10$BlgVs3zCB9urhQ2/qkvoQupxFB95UvYBNSXF.x1nGbPYnjRHKaoB6', 'admin', 1);
INSERT INTO user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO user_role (user_id, role_id) VALUES (1, 2);

insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('LMP', 'DuBuque Inc', 'Argentina');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('CSO', 'Hansen-Zemlak', 'Palestinian Territory');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('ONB', 'Predovic-Dickinson', 'Colombia');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('JER', 'Bechtelar LLC', 'China');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('CKK', 'Larkin-Baumbach', 'Thailand');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('MZG', 'Wiza-Corkery', 'Grenada');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('MEG', 'Green-O''Hara', 'Czech Republic');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('BWE', 'Cummings, Jacobs and Schuppe', 'Canada');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('CNS', 'Heidenreich and Sons', 'United States');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('TON', 'Fritsch, Abshire and O''Reilly', 'Ukraine');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('ZAH', 'Kozey LLC', 'Kenya');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('SRD', 'Nicolas Group', 'China');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('SFZ', 'Bauch Inc', 'Sierra Leone');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('SZW', 'Hermiston-Schoen', 'Russia');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('AZS', 'Runolfsdottir LLC', 'Kazakhstan');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('CTP', 'Abernathy, Prohaska and Casper', 'Mexico');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('GBI', 'Ratke-Williamson', 'China');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('LGO', 'Hirthe-Kutch', 'China');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('BEL', 'Miller-Skiles', 'China');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('IGB', 'Mayert LLC', 'China');

insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Tisma', 'Car Nicobar Air Force Station', 'Nicaragua');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Caherconlish', 'Bahawalnagar Airport', 'Ireland');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Washington', 'Eneabba Airport', 'United States');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Dawuhan', 'Putumayo Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Jinquan', 'Ruse Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Potongan', 'Manistee Co Blacker Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Oekuu', 'King Abdulaziz Air Base', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Shakhty', 'Belgaum Airport', 'Russia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Kazinka', 'Kaintiba Airport', 'Russia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Dushu', 'Tipton Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Ostrožac', 'Cabo Rojo Airport', 'Bosnia and Herzegovina');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Zhengyangshan', 'General Heriberto Jara International Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Petaling Jaya', 'Florø Airport', 'Malaysia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Valky', 'Kabalo Airport', 'Ukraine');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Wolofeo', 'Four Corners Regional Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Murtajih', 'Montpellier-Méditerranée Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Bordeaux', 'Ingham Airport', 'France');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Ugljan', 'Safia Airport', 'Croatia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Smiths Falls', 'Sand Point Airport', 'Canada');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Cikole', 'Fazenda São João Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Kortkeros', 'Haines Junction Airport', 'Russia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Báguanos', 'Chino Airport', 'Cuba');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Isfahan', 'Sharpe Field', 'Iran');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Phnom Penh', 'Teller Airport', 'Cambodia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Béboto', 'Hayward Executive Airport', 'Chad');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Tawan tawan', 'Jamnagar Airport', 'Philippines');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Morales', 'Hobart International Airport', 'Colombia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Tremembé', 'İncirlik Air Base', 'Brazil');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Van Nuys', 'Whyalla Airport', 'United States');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Krzeczów', 'Prieska Airport', 'Poland');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Maria', 'Exmouth Airport', 'Philippines');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Koktal', 'Port Hope Simpson Airport', 'Kazakhstan');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Thị Trấn Ngọc Lặc', 'Songea Airport', 'Vietnam');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Storvreta', 'Vorkuta Airport', 'Sweden');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Dengfeng', 'Vir Savarkar International Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Verdizela', 'Lauro Carneiro de Loyola Airport', 'Portugal');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Kudang', 'Bahia Piña Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Avignon', 'Aiken Regional Airport', 'France');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Lisičani', 'Namatanai Airport', 'Macedonia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Marne-la-Vallée', 'Corpus Christi International Airport', 'France');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Cabano', 'Plettenberg Bay Airport', 'Canada');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Xiamayu', 'Fredericton Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Seget', 'Bahawalpur Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Changjiangbu', 'Fort Frances Municipal Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Fenggao', 'Caviahue Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Ilyich', 'Space Coast Regional Airport', 'Kazakhstan');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Shah Alam', 'Southport Airport', 'Malaysia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Stare Juchy', 'Sim Airport', 'Poland');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Wang Thonglang', 'Coonabarabran Airport', 'Thailand');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Longzhou', 'Manja Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Nusajaya', 'Skardu Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Erlangkou', 'Comodoro Pedro Zanni Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Pandi', 'Monterey Peninsula Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Dampit', 'Novo Hamburgo Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Lishui', 'Mannheim-City Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Horlivka', 'Yanji Chaoyangchuan Airport', 'Ukraine');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Camangcamang', 'Pecos Municipal Airport', 'Philippines');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Tanahgrogot', 'Matamata Glider Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Oklahoma City', 'Sawan Airport', 'United States');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Foros de Salvaterra', 'Yellowknife Airport', 'Portugal');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Santiago de Cao', 'Gävle Sandviken Airport', 'Peru');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Kalávryta', 'Fincha Airport', 'Greece');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Vityazevo', 'Juanda International Airport', 'Russia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Sasebo', 'Seymour Airport', 'Japan');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Abelheira', 'Schwerin Parchim Airport', 'Portugal');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Shiziling', 'Bluefields Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Ailigandí', 'Red Deer Regional Airport', 'Panama');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Jaworzyna Śląska', 'San Javier Airport', 'Poland');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Luchegorsk', 'Ceres Airport', 'Russia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Vysoké nad Jizerou', 'Dirranbandi Airport', 'Czech Republic');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Upper San Mateo', 'Peace River Airport', 'Philippines');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Kobilje', 'Montreal / Pierre Elliott Trudeau International Airport', 'Slovenia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Yanghu', 'Roben Hood Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Taytay', 'Tongoa Airport', 'Philippines');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Paniówki', 'Satu Mare Airport', 'Poland');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Jiḩānah', 'Yellowknife Airport', 'Yemen');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Kramators’k', 'Bemolanga Airport', 'Ukraine');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Ritaebang', 'Whitecourt Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Thanh Chương', 'Akunaq Heliport', 'Vietnam');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Bua Yai', 'Tosontsengel Airport', 'Thailand');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Ostrowsko', 'Sultan Azlan Shah Airport', 'Poland');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Pluak Daeng', 'Lviv International Airport', 'Thailand');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Besançon', 'Tullahoma Regional Arpt/Wm Northern Field', 'France');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Libiąż', 'Rosella Plains Airport', 'Poland');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Wilmington', 'Alexander Field South Wood County Airport', 'United States');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Valbo', 'Licenciado Manuel Crescencio Rejon Int Airport', 'Sweden');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Maluso', 'Kalbarri Airport', 'Philippines');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Petrolera', 'Tarapoa Airport', 'Mexico');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Kostyantynivka', 'Comandante Ariston Pessoa Airport', 'Ukraine');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Carvalhos', 'Sulphur Springs Municipal Airport', 'Portugal');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Kranggan', 'Santander Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Orange', 'Nakhon Si Thammarat Airport', 'France');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Kuala Lumpur', 'Skeldon Airport', 'Malaysia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Barbosa', 'Pakuba Airfield', 'Colombia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Baraguá', 'Kiryat Shmona Airport', 'Cuba');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Barat', 'Cowley Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Bromma', 'Lester B. Pearson International Airport', 'Sweden');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Rauco', 'Walcha Airport', 'Chile');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Guanay', 'Larsen Bay Airport', 'Bolivia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Tanenofunan', 'Maio Airport', 'Indonesia');

insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (85, 73, '2025-06-27', '5:18:31', 884740, 19, 80, 50);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (81, 308, '2025-12-02', '15:32:34', 830169, 4, 87, 1);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (98, 387, '2025-07-01', '20:09:05', 143274, 10, 26, 71);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (91, 549, '2025-06-03', '7:29:49', 317208, 5, 57, 87);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (103, 109, '2025-11-19', '8:08:02', 763468, 10, 79, 73);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (103, 167, '2025-07-09', '14:03:42', 395683, 6, 81, 68);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (104, 351, '2025-11-28', '0:53:12', 955564, 19, 65, 54);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (126, 398, '2025-11-24', '0:20:39', 651404, 20, 13, 39);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (101, 261, '2025-11-09', '16:27:33', 200866, 9, 54, 81);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (84, 220, '2025-05-22', '22:38:55', 143196, 11, 27, 69);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (93, 152, '2025-04-15', '12:57:08', 452617, 7, 44, 94);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (124, 574, '2025-01-10', '7:30:48', 684813, 2, 82, 91);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (123, 171, '2025-12-01', '23:15:14', 197144, 16, 90, 24);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (90, 142, '2025-05-22', '6:24:28', 883514, 10, 40, 1);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (117, 510, '2025-03-11', '19:02:06', 577083, 17, 74, 1);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (117, 414, '2025-07-25', '18:26:35', 879237, 16, 12, 10);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (119, 148, '2025-07-19', '10:29:25', 372088, 14, 72, 54);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (99, 62, '2025-06-09', '16:04:51', 530409, 20, 71, 96);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (111, 336, '2025-08-22', '2:29:05', 899621, 1, 52, 79);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (121, 325, '2025-05-03', '6:54:59', 988346, 20, 47, 9);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (125, 246, '2025-04-11', '20:59:24', 726732, 14, 40, 17);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (121, 315, '2025-03-18', '14:27:57', 554897, 11, 84, 62);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (108, 102, '2024-12-03', '11:22:02', 345343, 2, 35, 39);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (110, 501, '2024-12-26', '16:48:14', 922479, 14, 54, 1);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (121, 528, '2025-01-03', '19:39:46', 427181, 18, 19, 21);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (89, 233, '2025-09-06', '0:34:49', 711243, 18, 57, 59);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (115, 449, '2024-12-27', '19:32:07', 607901, 13, 25, 25);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (129, 127, '2025-01-21', '5:03:51', 908124, 9, 20, 4);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (109, 266, '2025-11-25', '16:14:28', 347610, 8, 66, 76);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (92, 88, '2025-12-24', '6:51:04', 545428, 18, 90, 25);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (83, 564, '2025-10-07', '6:18:09', 252188, 18, 11, 82);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (80, 587, '2025-01-21', '17:59:57', 510806, 16, 82, 75);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (127, 141, '2025-12-25', '18:33:30', 393272, 10, 52, 95);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (117, 440, '2025-06-12', '10:22:11', 878054, 7, 90, 29);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (88, 219, '2025-08-12', '9:46:16', 740530, 3, 41, 87);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (104, 214, '2025-07-16', '6:46:06', 816684, 3, 49, 31);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (91, 189, '2025-04-01', '8:04:35', 162761, 12, 57, 85);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (130, 129, '2025-04-16', '2:37:15', 577707, 19, 1, 59);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (99, 580, '2025-08-10', '6:42:35', 840501, 18, 60, 92);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (124, 443, '2025-10-13', '13:31:19', 875663, 12, 10, 96);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (114, 168, '2025-02-05', '18:15:03', 617674, 17, 10, 98);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (119, 171, '2025-08-08', '15:44:23', 763413, 3, 64, 21);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (130, 66, '2025-09-09', '2:24:21', 202314, 14, 83, 98);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (121, 490, '2025-12-15', '7:03:01', 874100, 5, 80, 67);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (102, 423, '2025-10-06', '17:13:08', 603470, 11, 31, 23);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (114, 467, '2025-02-03', '19:17:31', 475487, 3, 2, 71);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (115, 138, '2025-07-25', '6:38:42', 224525, 8, 37, 85);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (83, 589, '2025-01-01', '17:01:45', 426715, 20, 68, 90);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (100, 203, '2024-12-01', '16:04:06', 711991, 8, 44, 24);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (126, 323, '2025-07-15', '5:27:41', 938668, 10, 97, 40);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (92, 425, '2025-02-06', '20:04:31', 437849, 18, 51, 70);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (123, 484, '2024-12-31', '5:28:25', 425605, 20, 50, 2);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (130, 91, '2025-01-22', '7:26:38', 111453, 4, 56, 2);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (87, 74, '2025-07-24', '15:36:14', 851166, 17, 77, 71);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (121, 368, '2025-07-17', '23:04:39', 301854, 8, 37, 46);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (111, 122, '2025-01-03', '13:41:20', 257223, 7, 5, 39);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (127, 353, '2025-03-11', '13:31:27', 651696, 12, 92, 16);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (116, 495, '2025-03-31', '6:18:01', 179866, 3, 16, 65);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (95, 232, '2025-07-15', '21:09:52', 192636, 13, 10, 47);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (91, 118, '2025-08-13', '9:13:11', 712171, 13, 77, 48);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (96, 340, '2025-09-29', '9:05:17', 172791, 19, 71, 39);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (113, 193, '2025-09-03', '15:14:02', 70820, 20, 59, 16);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (101, 377, '2025-04-22', '0:07:39', 996478, 8, 87, 43);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (119, 239, '2025-02-07', '21:56:14', 331205, 4, 90, 16);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (101, 242, '2025-02-07', '13:28:32', 302264, 6, 39, 68);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (84, 313, '2025-01-20', '5:06:57', 361733, 12, 62, 95);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (117, 409, '2025-02-09', '20:20:16', 344567, 10, 60, 76);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (116, 290, '2025-09-29', '6:43:31', 936380, 11, 90, 53);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (83, 85, '2025-12-21', '6:04:06', 744045, 20, 37, 20);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (93, 549, '2025-04-18', '12:00:48', 865312, 13, 83, 90);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (112, 457, '2025-01-02', '7:48:56', 448787, 14, 11, 72);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (116, 201, '2025-12-02', '19:08:20', 732463, 4, 83, 61);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (113, 165, '2025-06-17', '4:39:46', 892947, 2, 63, 91);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (85, 127, '2025-03-28', '8:17:46', 898140, 14, 77, 62);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (92, 262, '2025-07-30', '13:33:53', 505060, 10, 88, 35);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (101, 577, '2025-05-07', '22:40:09', 881626, 19, 77, 27);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (86, 485, '2025-10-19', '18:39:01', 437898, 16, 21, 46);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (85, 283, '2025-07-26', '9:28:32', 117532, 14, 90, 26);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (95, 134, '2025-01-25', '7:16:53', 264638, 14, 56, 42);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (113, 412, '2025-08-03', '22:38:15', 860288, 11, 100, 17);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (82, 481, '2025-10-21', '12:23:34', 703141, 3, 65, 95);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (85, 556, '2025-06-24', '18:29:18', 575439, 12, 26, 57);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (115, 548, '2025-04-29', '8:44:55', 571849, 3, 93, 42);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (119, 64, '2024-12-17', '14:51:38', 568300, 14, 16, 88);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (104, 247, '2025-04-26', '13:15:56', 740637, 2, 82, 91);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (122, 494, '2025-10-20', '8:21:27', 392136, 1, 47, 63);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (121, 352, '2025-02-07', '11:12:34', 956564, 9, 98, 48);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (113, 508, '2025-10-30', '8:54:13', 165561, 1, 58, 14);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (89, 545, '2025-10-14', '21:53:16', 241218, 20, 9, 26);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (98, 418, '2025-01-26', '1:05:48', 290117, 12, 65, 3);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (119, 496, '2025-07-04', '2:16:48', 722293, 16, 19, 27);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (109, 207, '2025-03-17', '3:36:28', 982711, 3, 7, 47);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (116, 424, '2025-02-05', '12:29:45', 540672, 1, 2, 46);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (94, 580, '2025-04-17', '8:39:04', 239851, 6, 84, 62);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (106, 409, '2025-03-05', '15:24:58', 180528, 9, 90, 21);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (83, 309, '2025-11-20', '1:27:37', 266297, 7, 95, 92);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (86, 100, '2025-12-05', '10:02:16', 108213, 10, 23, 16);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (106, 125, '2025-10-11', '11:03:09', 104756, 8, 49, 66);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (120, 272, '2025-06-09', '8:24:08', 646768, 15, 49, 58);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, precio_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (86, 597, '2025-01-14', '13:42:02', 236056, 13, 42, 27);