insert into roles (name) values ('ROLE_USER');
insert into roles (name) values ('ROLE_ADMIN');

insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('LMP', 'DuBuque Inc', 'Argentina');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('CSO', 'Hansen-Zemlak', 'Palestinian Territory');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('ONB', 'Predovic-Dickinson', 'Colombia');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('JER', 'Bechtelar LLC', 'China');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('CKK', 'Larkin-Baumbach', 'Thailand');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('MZG', 'Wiza-Corkery', 'Grenada');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('MEG', 'Green-O''Hara', 'Czech Republic');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('BWE', 'Cummings, Jacobs and Schuppe', 'Canada');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('CNS', 'Heidenreich and Sons', 'United States');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('TON', 'Fritsch, Abshire and O''Reilly', 'Ukraine');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('ZAH', 'Kozey LLC', 'Kenya');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('SRD', 'Nicolas Group', 'China');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('SFZ', 'Bauch Inc', 'Sierra Leone');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('SZW', 'Hermiston-Schoen', 'Russia');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('AZS', 'Runolfsdottir LLC', 'Kazakhstan');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('CTP', 'Abernathy, Prohaska and Casper', 'Mexico');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('GBI', 'Ratke-Williamson', 'China');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('LGO', 'Hirthe-Kutch', 'China');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('BEL', 'Miller-Skiles', 'China');
insert into aerolineas (codigo_aerolinea, nombre_aerolinea, pais_origen_aerolinea) values ('IGB', 'Mayert LLC', 'China');

insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Tisma', 'Car Nicobar Air Force Station', 'Nicaragua');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Caherconlish', 'Bahawalnagar Airport', 'Ireland');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Washington', 'Eneabba Airport', 'United States');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Dawuhan', 'Putumayo Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Jinquan', 'Ruse Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Potongan', 'Manistee Co Blacker Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Oekuu', 'King Abdulaziz Air Base', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Shakhty', 'Belgaum Airport', 'Russia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Kazinka', 'Kaintiba Airport', 'Russia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Dushu', 'Tipton Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Ostrožac', 'Cabo Rojo Airport', 'Bosnia and Herzegovina');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Zhengyangshan', 'General Heriberto Jara International Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Petaling Jaya', 'Florø Airport', 'Malaysia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Valky', 'Kabalo Airport', 'Ukraine');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Wolofeo', 'Four Corners Regional Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Murtajih', 'Montpellier-Méditerranée Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Bordeaux', 'Ingham Airport', 'France');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Ugljan', 'Safia Airport', 'Croatia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Smiths Falls', 'Sand Point Airport', 'Canada');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Cikole', 'Fazenda São João Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Kortkeros', 'Haines Junction Airport', 'Russia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Báguanos', 'Chino Airport', 'Cuba');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Isfahan', 'Sharpe Field', 'Iran');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Phnom Penh', 'Teller Airport', 'Cambodia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Béboto', 'Hayward Executive Airport', 'Chad');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Tawan tawan', 'Jamnagar Airport', 'Philippines');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Morales', 'Hobart International Airport', 'Colombia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Tremembé', 'İncirlik Air Base', 'Brazil');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Van Nuys', 'Whyalla Airport', 'United States');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Krzeczów', 'Prieska Airport', 'Poland');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Maria', 'Exmouth Airport', 'Philippines');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Koktal', 'Port Hope Simpson Airport', 'Kazakhstan');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Thị Trấn Ngọc Lặc', 'Songea Airport', 'Vietnam');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Storvreta', 'Vorkuta Airport', 'Sweden');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Dengfeng', 'Vir Savarkar International Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Verdizela', 'Lauro Carneiro de Loyola Airport', 'Portugal');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Kudang', 'Bahia Piña Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Avignon', 'Aiken Regional Airport', 'France');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Lisičani', 'Namatanai Airport', 'Macedonia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Marne-la-Vallée', 'Corpus Christi International Airport', 'France');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Cabano', 'Plettenberg Bay Airport', 'Canada');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Xiamayu', 'Fredericton Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Seget', 'Bahawalpur Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Changjiangbu', 'Fort Frances Municipal Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Fenggao', 'Caviahue Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Ilyich', 'Space Coast Regional Airport', 'Kazakhstan');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Shah Alam', 'Southport Airport', 'Malaysia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Stare Juchy', 'Sim Airport', 'Poland');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Wang Thonglang', 'Coonabarabran Airport', 'Thailand');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Longzhou', 'Manja Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Nusajaya', 'Skardu Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Erlangkou', 'Comodoro Pedro Zanni Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Pandi', 'Monterey Peninsula Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Dampit', 'Novo Hamburgo Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Lishui', 'Mannheim-City Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Horlivka', 'Yanji Chaoyangchuan Airport', 'Ukraine');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Camangcamang', 'Pecos Municipal Airport', 'Philippines');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Tanahgrogot', 'Matamata Glider Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Oklahoma City', 'Sawan Airport', 'United States');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Foros de Salvaterra', 'Yellowknife Airport', 'Portugal');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Santiago de Cao', 'Gävle Sandviken Airport', 'Peru');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Kalávryta', 'Fincha Airport', 'Greece');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Vityazevo', 'Juanda International Airport', 'Russia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Sasebo', 'Seymour Airport', 'Japan');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Abelheira', 'Schwerin Parchim Airport', 'Portugal');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Shiziling', 'Bluefields Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Ailigandí', 'Red Deer Regional Airport', 'Panama');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Jaworzyna Śląska', 'San Javier Airport', 'Poland');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Luchegorsk', 'Ceres Airport', 'Russia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Vysoké nad Jizerou', 'Dirranbandi Airport', 'Czech Republic');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Upper San Mateo', 'Peace River Airport', 'Philippines');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Kobilje', 'Montreal / Pierre Elliott Trudeau International Airport', 'Slovenia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Yanghu', 'Roben Hood Airport', 'China');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Taytay', 'Tongoa Airport', 'Philippines');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Paniówki', 'Satu Mare Airport', 'Poland');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Jiḩānah', 'Yellowknife Airport', 'Yemen');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Kramators’k', 'Bemolanga Airport', 'Ukraine');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Ritaebang', 'Whitecourt Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Thanh Chương', 'Akunaq Heliport', 'Vietnam');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Bua Yai', 'Tosontsengel Airport', 'Thailand');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Ostrowsko', 'Sultan Azlan Shah Airport', 'Poland');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Pluak Daeng', 'Lviv International Airport', 'Thailand');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Besançon', 'Tullahoma Regional Arpt/Wm Northern Field', 'France');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Libiąż', 'Rosella Plains Airport', 'Poland');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Wilmington', 'Alexander Field South Wood County Airport', 'United States');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Valbo', 'Licenciado Manuel Crescencio Rejon Int Airport', 'Sweden');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Maluso', 'Kalbarri Airport', 'Philippines');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Petrolera', 'Tarapoa Airport', 'Mexico');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Kostyantynivka', 'Comandante Ariston Pessoa Airport', 'Ukraine');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Carvalhos', 'Sulphur Springs Municipal Airport', 'Portugal');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Kranggan', 'Santander Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Orange', 'Nakhon Si Thammarat Airport', 'France');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Kuala Lumpur', 'Skeldon Airport', 'Malaysia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Barbosa', 'Pakuba Airfield', 'Colombia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Baraguá', 'Kiryat Shmona Airport', 'Cuba');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Barat', 'Cowley Airport', 'Indonesia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Bromma', 'Lester B. Pearson International Airport', 'Sweden');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Rauco', 'Walcha Airport', 'Chile');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Guanay', 'Larsen Bay Airport', 'Bolivia');
insert into aeropuertos (ciudad_aeropuerto, nombre_aeropuerto, pais_aeropuerto) values ('Tanenofunan', 'Maio Airport', 'Indonesia');

insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (129, 498, '2025-10-07', '2:32:25', 10, 69, 29);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (130, 321, '2025-05-05', '13:14:44', 13, 59, 99);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (120, 232, '2025-07-02', '21:57:21', 20, 26, 36);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (104, 327, '2025-03-16', '2:08:13', 17, 91, 15);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (105, 322, '2025-02-01', '7:36:12', 1, 5, 37);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (121, 173, '2025-03-27', '2:22:23', 8, 94, 96);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (126, 77, '2025-06-02', '22:21:33', 7, 85, 58);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (129, 359, '2025-05-04', '23:33:51', 14, 62, 5);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (116, 347, '2025-05-14', '1:54:52', 3, 58, 73);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (130, 270, '2025-09-22', '2:40:54', 9, 63, 12);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (130, 211, '2025-12-21', '5:36:36', 19, 57, 32);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (109, 213, '2025-08-03', '16:44:30', 15, 59, 46);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (109, 211, '2025-01-12', '4:41:34', 6, 3, 24);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (121, 417, '2025-09-17', '0:19:27', 16, 23, 70);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (121, 115, '2025-03-09', '2:35:54', 3, 80, 68);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (124, 395, '2025-03-26', '18:44:50', 5, 80, 92);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (120, 62, '2025-02-14', '9:32:05', 4, 98, 59);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (121, 343, '2025-09-17', '23:27:33', 8, 97, 61);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (128, 73, '2025-12-03', '6:30:46', 3, 13, 19);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (113, 344, '2025-09-26', '11:34:04', 18, 42, 76);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (130, 227, '2025-12-30', '15:15:42', 15, 80, 39);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (112, 553, '2025-01-23', '8:54:50', 3, 15, 32);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (119, 404, '2025-02-20', '14:40:47', 2, 97, 83);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (128, 426, '2025-06-27', '21:14:59', 4, 72, 59);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (123, 520, '2025-04-25', '1:12:49', 8, 21, 14);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (106, 95, '2025-03-19', '17:34:10', 16, 50, 58);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (103, 281, '2025-09-21', '18:15:01', 16, 23, 55);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (110, 299, '2025-06-15', '5:45:28', 6, 14, 35);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (126, 268, '2025-10-27', '15:28:38', 11, 13, 32);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (115, 262, '2025-06-08', '10:35:29', 12, 27, 27);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (111, 352, '2025-05-26', '22:55:22', 18, 81, 39);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (116, 67, '2025-04-17', '8:05:29', 18, 73, 45);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (115, 305, '2025-01-28', '1:58:24', 16, 74, 51);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (122, 283, '2025-07-05', '0:41:39', 8, 8, 31);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (120, 60, '2025-01-02', '20:06:38', 13, 100, 6);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (102, 477, '2025-05-03', '21:59:07', 3, 48, 42);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (121, 534, '2025-11-26', '14:01:38', 16, 90, 76);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (107, 185, '2025-06-24', '21:34:46', 2, 74, 91);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (119, 414, '2025-04-14', '20:52:11', 14, 24, 25);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (100, 105, '2025-09-10', '5:05:32', 8, 23, 33);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (104, 496, '2025-05-02', '3:11:26', 13, 36, 3);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (111, 397, '2025-03-15', '11:52:51', 19, 90, 35);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (108, 151, '2025-10-19', '8:29:12', 15, 27, 34);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (109, 526, '2025-02-14', '13:42:58', 15, 99, 65);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (105, 423, '2025-11-24', '23:13:59', 11, 43, 100);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (117, 165, '2025-04-04', '9:35:25', 12, 88, 45);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (116, 196, '2025-09-13', '6:09:27', 3, 22, 26);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (109, 463, '2025-10-06', '22:32:10', 2, 57, 58);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (105, 200, '2025-02-13', '9:04:25', 3, 97, 73);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (107, 333, '2025-01-28', '16:21:38', 10, 92, 43);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (117, 84, '2025-02-19', '20:33:22', 14, 39, 2);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (120, 595, '2025-03-12', '5:01:12', 4, 23, 48);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (111, 94, '2025-12-24', '3:48:34', 18, 30, 69);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (100, 73, '2025-01-29', '8:08:10', 7, 46, 63);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (109, 476, '2025-09-10', '17:03:37', 17, 17, 20);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (116, 97, '2025-11-16', '10:22:41', 6, 51, 88);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (108, 70, '2025-01-17', '14:42:05', 18, 55, 86);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (110, 410, '2025-04-04', '21:26:35', 19, 90, 86);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (102, 209, '2025-10-02', '17:22:25', 3, 61, 46);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (116, 500, '2025-05-06', '22:56:12', 4, 25, 45);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (122, 69, '2025-09-07', '8:28:37', 6, 23, 24);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (101, 576, '2025-12-07', '8:54:59', 15, 41, 70);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (123, 351, '2025-02-09', '17:19:19', 18, 9, 12);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (123, 190, '2025-12-04', '23:02:03', 10, 66, 89);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (115, 310, '2025-02-03', '18:28:13', 12, 90, 93);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (118, 556, '2025-08-06', '16:21:49', 16, 54, 35);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (106, 417, '2025-12-01', '6:15:54', 16, 55, 25);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (115, 439, '2025-02-05', '1:31:18', 17, 4, 23);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (118, 526, '2025-02-02', '18:13:57', 3, 23, 13);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (111, 442, '2025-07-04', '16:29:11', 1, 58, 65);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (104, 417, '2025-11-23', '3:40:26', 5, 20, 24);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (116, 286, '2025-11-02', '5:51:35', 20, 57, 65);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (127, 580, '2025-03-27', '20:09:23', 4, 24, 52);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (127, 333, '2025-12-31', '9:24:12', 15, 94, 97);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (128, 108, '2025-06-04', '8:20:46', 10, 39, 40);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (107, 131, '2025-08-31', '10:58:39', 16, 46, 15);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (103, 69, '2025-01-08', '7:01:21', 18, 58, 17);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (104, 223, '2025-01-10', '14:19:30', 11, 4, 27);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (114, 510, '2025-03-30', '3:54:32', 11, 21, 92);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (103, 311, '2025-11-07', '13:48:51', 11, 28, 31);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (111, 399, '2025-06-02', '0:30:08', 19, 62, 14);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (102, 585, '2025-06-06', '2:31:01', 13, 46, 87);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (122, 514, '2025-07-11', '7:17:46', 12, 70, 21);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (106, 555, '2025-02-03', '4:54:27', 14, 80, 19);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (112, 158, '2025-09-04', '17:40:29', 18, 23, 22);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (112, 295, '2025-06-22', '23:00:01', 17, 82, 20);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (130, 484, '2025-05-16', '20:27:27', 12, 85, 68);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (124, 311, '2025-10-20', '21:54:52', 18, 71, 72);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (125, 250, '2025-12-04', '17:56:46', 11, 28, 42);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (101, 164, '2025-04-09', '13:48:14', 1, 30, 46);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (115, 262, '2025-02-05', '4:29:18', 4, 10, 33);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (108, 247, '2025-07-15', '9:07:46', 7, 62, 41);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (127, 382, '2025-06-13', '0:04:02', 17, 32, 66);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (110, 108, '2025-01-28', '22:11:07', 13, 95, 79);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (121, 473, '2025-09-01', '10:31:29', 5, 57, 51);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (119, 191, '2025-07-18', '10:30:56', 16, 38, 28);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (112, 548, '2025-10-28', '3:40:54', 7, 71, 12);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (104, 60, '2025-01-31', '17:47:40', 15, 38, 52);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (111, 208, '2025-11-09', '6:49:52', 19, 95, 8);
insert into vuelos (capacidad_vuelo, duracion_minutos_vuelo, fecha_salida_vuelo, hora_salida_vuelo, id_aerolinea, id_aeropuerto_destino, id_aeropuerto_origen) values (103, 580, '2025-04-16', '12:11:33', 20, 52, 71);
